[package]
name = "cw-pagination"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = "1.2.6"
cw-storage-plus = "1.0.1"
cosmwasm-schema = "1.2.6"